Create Table users (
  id Bigint Generated By Default As Identity Primary Key,
  name Text Not Null,
  role Text Not Null Check (role In ('DOCTOR', 'NURSE', 'PATIENT')),
  status Text Not Null Check (status In ('ACTIVE', 'INACTIVE')),
  joined_date Date Not Null,
  last_active Date Not Null,
  appointments_count Int Not Null Default 0,
  is_prime Boolean Not Null Default False,
  email Text Not Null,
  phone_code Int Not Null,
  phone_number Text Not Null
);

Create Table family_members (
  id Bigint Generated Always As Identity Primary Key,
  user_id Bigint Not Null,
  name Text Not Null,
  relation Text Not Null,
  phone_code Int Not Null,
  phone_number Text Not Null,
  dob Date Not Null,

  Constraint fk_family_members_user
    Foreign Key (user_id)
    References users(id)
    On Delete Cascade
);
