Create Table users (
  id Bigint Generated By Default As Identity Primary Key,
  name Text Not Null,
  role Text Not Null Check (role In ('DOCTOR', 'NURSE', 'PATIENT')),
  status Text Not Null Check (status In ('ACTIVE', 'INACTIVE')),
  joined_date Date Not Null,
  last_active Date Not Null,
  appointments_count Int Not Null Default 0,
  is_prime Boolean Not Null Default False,
  email Text,
  phone_number Text,
  gender Text Not Null Check (gender In ('MALE', 'FEMALE', 'NON_BINARY', 'PREFER_NOT_TO_SAY')),
  dob Date Not Null,
  blood_group Text Check (blood_group In (
    'A_POSITIVE',
    'A_NEGATIVE',
    'B_POSITIVE',
    'B_NEGATIVE',
    'AB_POSITIVE',
    'AB_NEGATIVE',
    'O_POSITIVE',
    'O_NEGATIVE'
  )),
  address Text,
  postal_code Text,
  city Text,
  state Text,
  country Text
);

Create Table family_members (
  id Bigint Generated Always As Identity Primary Key,
  user_id Bigint Not Null,
  name Text Not Null,
  relation Text Not Null,
  phone_number Text Not Null,
  dob Date Not Null,

  Constraint fk_family_members_user
    Foreign Key (user_id)
    References users(id)
    On Delete Cascade
);
