spring.application.name=user_mgmt

spring.datasource.url=jdbc:postgresql://localhost:5432/jiva
spring.datasource.username=deepak
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

spring.jpa.open-in-view=false
