Create Table users (
  id Bigint Generated By Default As Identity Primary Key,
  name Text Not Null,
  role Text Check (role In ('DOCTOR', 'NURSE', 'PATIENT')) Default 'PATIENT',
  status Text Check (status In ('ACTIVE', 'INACTIVE')) Default 'ACTIVE',
  joined_date Date Default Current_date,
  last_active Date Default Current_date,
  appointments_count Int Not Null Default 0,
  is_prime Boolean Not Null Default False,
  email Text,
  phone_number Text,
  gender Text Check (gender In ('MALE', 'FEMALE', 'NON_BINARY', 'PREFER_NOT_TO_SAY')),
  dob Date,
  blood_group Text Check (blood_group In (
    'A_POSITIVE',
    'A_NEGATIVE',
    'B_POSITIVE',
    'B_NEGATIVE',
    'AB_POSITIVE',
    'AB_NEGATIVE',
    'O_POSITIVE',
    'O_NEGATIVE'
  )),
  address Text,
  postal_code Text,
  city Text,
  state Text,
  country Text
);

Create Table family_members (
  id Bigint Generated Always As Identity Primary Key,
  user_id Bigint Not Null,
  name Text Not Null,
  relation Text Not Null,
  phone_number Text,
  dob Date,

  Constraint fk_family_members_user
    Foreign Key (user_id)
    References users(id)
    On Delete Cascade
);
